// Integration tests: run the full C++ FEFF pipeline for each material and
// compare output files against Fortran baselines.
//
// Work directory structure mirrors Fortran tests/:
//   tests/integration/work/<Material>/
//     baseline/noSCF/     ← copied from Fortran
//     baseline/withSCF/   ← copied from Fortran
//     feff.inp            ← copied from baseline/noSCF/
//     chi.dat             ← C++ output (generated by pipeline)
//     xmu.dat             ← C++ output
//     feffNNNN.dat        ← C++ output

#include "test_helpers.hpp"

#include <filesystem>
#include <string>

// Pipeline entry point
#include "../../src/pipeline/feff_pipeline.hpp"

namespace fs = std::filesystem;

// ============================================================================
// Parameterized fixture: one test instance per material
// ============================================================================
class PipelineTest : public ::testing::TestWithParam<std::string> {
protected:
    std::string material;
    std::string work_dir;
    std::string baseline_dir;
    fs::path original_cwd;

    void SetUp() override {
        material = GetParam();

        // Set up the work directory mirroring the Fortran test structure:
        // copies baseline/noSCF/ and baseline/withSCF/ from Fortran,
        // plus feff.inp at the material root
        feff::test::setup_material_work_dir(material);

        work_dir = feff::test::get_material_work_dir(material);
        baseline_dir = feff::test::get_baseline_dir(material);  // work dir baseline

        ASSERT_TRUE(fs::is_directory(baseline_dir))
            << "Baseline directory missing: " << baseline_dir;
        ASSERT_TRUE(fs::exists(work_dir + "/feff.inp"))
            << "feff.inp missing in work dir: " << work_dir;

        // Change to work directory (pipeline reads/writes relative to cwd)
        original_cwd = fs::current_path();
        fs::current_path(work_dir);
    }

    void TearDown() override {
        fs::current_path(original_cwd);
        // Work directories persist for inspection under tests/integration/work/
    }
};

// ---------------------------------------------------------------------------
// Full pipeline test (noSCF mode)
// ---------------------------------------------------------------------------
TEST_P(PipelineTest, NoSCF) {
    // Run the complete FEFF pipeline
    feff::pipeline::PipelineConfig config;
    config.input_file = "feff.inp";
    config.verbose = false;

    int rc = feff::pipeline::run_feff(config);
    EXPECT_EQ(rc, 0) << "Pipeline returned error code " << rc
                      << " for material " << material;

    if (rc != 0) return;

    // Compare output files against baseline (in the local baseline/ copy)
    std::string bl = baseline_dir;

    // chi.dat: column 1 (chi)
    if (feff::test::file_exists(bl + "/chi.dat") &&
        feff::test::file_exists(work_dir + "/chi.dat")) {
        feff::test::compare_data_files(bl + "/chi.dat", work_dir + "/chi.dat",
                                       1, 0.10, material + " chi.dat col 1 (chi)");
    }

    // xmu.dat: column 3 (xmu)
    if (feff::test::file_exists(bl + "/xmu.dat") &&
        feff::test::file_exists(work_dir + "/xmu.dat")) {
        feff::test::compare_data_files(bl + "/xmu.dat", work_dir + "/xmu.dat",
                                       3, 0.10, material + " xmu.dat col 3 (xmu)");
    }

    // paths.dat: existence
    if (feff::test::file_exists(bl + "/paths.dat")) {
        EXPECT_TRUE(feff::test::file_exists(work_dir + "/paths.dat"))
            << material << ": paths.dat not generated";
    }

    // files.dat: existence
    if (feff::test::file_exists(bl + "/files.dat")) {
        EXPECT_TRUE(feff::test::file_exists(work_dir + "/files.dat"))
            << material << ": files.dat not generated";
    }

    // feff0001.dat: columns 2 (|feff|) and 3 (phase)
    if (feff::test::file_exists(bl + "/feff0001.dat") &&
        feff::test::file_exists(work_dir + "/feff0001.dat")) {
        feff::test::compare_data_files(bl + "/feff0001.dat",
                                       work_dir + "/feff0001.dat",
                                       2, 0.10, material + " feff0001.dat col 2 (|feff|)");
        feff::test::compare_data_files(bl + "/feff0001.dat",
                                       work_dir + "/feff0001.dat",
                                       3, 0.10, material + " feff0001.dat col 3 (phase)");
    }
}

// ---------------------------------------------------------------------------
// Register all 8 materials
// ---------------------------------------------------------------------------
INSTANTIATE_TEST_SUITE_P(Materials, PipelineTest,
    ::testing::Values("Copper", "NiO", "UO2", "Zircon",
                      "ferrocene", "bromoadamantane", "LCO-para", "LCO-perp"),
    [](const ::testing::TestParamInfo<std::string>& info) {
        std::string name = info.param;
        std::replace(name.begin(), name.end(), '-', '_');
        return name;
    });
